apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:noLT5ewI30MEqxwuL6dbAIlZlj8nqg68OEETFkb8KDdwBb6SjqFYv7pPsCzlYH17tqHxIvZjGP1Rp7XQK6DezB6LuumYRkdlXg+6v8Do/tJFLStOqZjpsX0xLiPaT7dEzodrpiM9OW0Sxx/1ImqJNpFsGP8MlLb8IfP/8vWfineXsZUoFHhdNL7tSpdNH9oqXwIwVVs1pnVMAVoxZ9XAw9GkHN82PXn8syT/rVfIjTI4WsIIH8AeTcNwGc+Ar4qJsfYCuJaAS6jzqYPmDyOtYMoMfL1mgaKo91aZ+CdhAs+5WHpnQjmTB3yv4/o=,iv:wrVsxII60xknXseChhfUTCHKNT+vY9VE29Kk8EoDGmQ=,tag:OcosIB0+nz45mzVPa15D+A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyODRuNkllT3JmbWI3VnRP
            aldYbWxMVXBPZDZwNTdSUXFlenMrU0VKam1vCkpMeVlFbGdZSlFxSGJhdlY1THBq
            eDhvUStLZ3ZkbW80NXpUcGl5YlExb2sKLS0tIEVqNkx3SFBEbHlWQy9KR1lOdWMx
            K040SUZrVUFGMXBGMU14enhGc0g1YlEKGMy4WnyxfTwlaueRQvgJdyra9SgSUAjv
            RkW/NoobQdtNaC4i8hoMqimy3IQvAvqiTZEzA5wWj71BYeoSjhxGKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T07:28:59Z"
    mac: ENC[AES256_GCM,data:FFLMhj3bmzISDjJy4PoGnkqs/wv2Tl/p80Npp1rhiGSQV9rKmqLxPN1sQjoa9K8PtmjtiVBakn9CPSeh35b6I+qiAYIx7YvxxnTKzk6zv8D+dLxjecWy7eeNGA4oGAZVx4aQhbR5pfjb0INm7kxlb8OelmnKUMfsqAMvnYxMKfA=,iv:ls7RHhDCIZtitpQzwmbcTHfXt0wUUpzalxx04lEnul0=,tag:cRco1iBU5lHWgNmK8S/P3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
