apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:+ElOzDiZeTfsnVsK3JpAw9wPZsLOokP4SXXMezr44wmvU1E6ANG0i48jKU3XDx9BjvouOVh9RKgUKT/t9SbTskQtGuUEppR74Yd1s7DDEnp6R8xAPzUL8+3JJg2OGjzFH8BvZ4vyGfrBnripOPfSSxYLFhTf5WrVlqCCV3xhOkvL8wnOyOFRdqOBRwDnTikHDWlxtSQWBhrF5qw12FQ320GnSArPx4v85RAOPI65fVKZmDygTuRaUekOul4s/tTofu4MTP5m5aMOqRIILjc/F5vZT+Sdr1C+O93GJmowv/gg98yiWAt7Kikns/M=,iv:UBnLBH/w7C5Vaj08eU/bPVallnV/3olM6h3U0RSmwWg=,tag:cRGfLUHAxuq9EpZ4SgEAhg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTktKdkpKaVpuUjFpVnd5
            RmdhRytSRkhWTjc4RjU1cStVNDRVOURwOEhvCldjci8yR3FZK0dJOXcwOStYaHZi
            Mkg2c1d1WmdOZ29TVlRlVmdadjBqaHcKLS0tIFdRUTU0WldzcTduUGc5djlVa0k5
            VU8vblh4Ui9POEtZUGxJQmhRSE1IWlEKoNI5ljlAAwDrejtfg8+pyhrb9JxqQUlh
            l77NYGM1p9lJJNMK400wGoOMvJzxJoU0KZcAnXOHNEFXKH5Z/YN+fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:11:12Z"
    mac: ENC[AES256_GCM,data:IqtPTY8d6SODeLWhsdcbO8ZG31filBZ1iYoPWL7TF67ArFqYXmN9/plfnub2t0YbO4W9G18FjrPbh8ACNeKud5oEVmljcKx4UmtB15bRV3iNLCP6PXAzwjoZHUEokygLPoA2U0B50Pq0hvBYppoyrK2ktPkHIe9Vx8HShvhYdec=,iv:BAC1tuiLJNS2hBaQ/a2abopTDbWX+3ww8avdKoBE5ns=,tag:UEP/UUzQjC507eVLCGu93w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
