apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Oxep+i/Z9wQx7u4/Xrbqaw==,iv:5nudrkvFBSuz/ILMByZ89ivFhrr9fGS77Wsy/DNECJ4=,tag:c1GuPTknx3g5FudP25n3Gg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:SI47mie1Jg+d2NHDvEXY0yXutzE=,iv:lEESuw2nlVrgQ4b8hf5ghkrr1HtWfzty9LZZmiiMayg=,tag:E5AXBGSwO41xj3UcqtYWnQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
    namespace: linkding
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cW1vMTIvMXF6UTl2Zjg2
            R2ZSazVBT0I3dG5EZGJ3MnhFZkxUL3E2N2lVCmxxWkRLOGdieEliL3Q0bjdxTUpy
            cUNwSGVpYmlQTzdxdTdqdXpnYURsREUKLS0tIGhpUDF2Q0x4UWwzc1hkUG9Bb0c3
            aXg3cXlTWHBqUm82NjdOa3hsRUY1R1kKOueHXIOy1OMkBKVLlhqP3J/fpNFk5n4L
            BW6Kzko+Z3Oy58zNfM9H7HqHjEv1k1qPLCS8/bVcWGsUhzObT3MOWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T18:14:24Z"
    mac: ENC[AES256_GCM,data:EVfawYkJr15n6i1M92URGkGZT8JdROKjIHr/rVUCRSHfiMEUDVKYzqHxKLBv1r/0Mckb6n5a1SXN7l2JYp4ZVZxsaa88AN1wHi9TP8sNIpHP6AdDmRUC/TZ1N1LCZqmBBhuS8WUvOQRTZnNEUIf4gicuQro06HhwIkuOmestDtE=,iv:iy/VfeQPjmRPjIbje1I+x1ANQIYmbb0e5ef/u0cQhts=,tag:7x03PWYrLz3kBy0h6bXfww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
