apiVersion: v1
data:
    password: ENC[AES256_GCM,data:NYBrVXpPoyw=,iv:G/BL3Eb2SkWdjwHf4x+9a+cT9IchlmGIRX66xe2fcrA=,tag:6rj3jyDJzzS0Kbsy1TDWTQ==,type:str]
    user: ENC[AES256_GCM,data:mWfmXlNPI+c=,iv:WIl/ADp9cVHfsNa2cI+7d6hKTL4ntXmS0HExzFK1N1I=,tag:AkpQRUI1jtpBD+uAY2ocJg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MVliREpCMEgvVktVTTYv
            R1ZhbjhZRW5QdWM4OFNPQUVvb09TTEQ5UlJFClRGNjRvZlVuZEZpSW9wNXVDSFZl
            VmxHcmVidUZWT01LRWFKc3BuVmdsclkKLS0tIEY1ekFNV0k4eXBIZzQrc1l5c1JM
            M09SQjh6RUdpbExjSHFrcXEvcTdNYlUK66R5A/D7lI9Pz+FrE50xLzrPMuDOfQrn
            ZT2Xi4r0vhzV6aQW5bSXCacCZzjIqvTfY9bxDq/X7ecS/InrsKZe6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-09T07:33:12Z"
    mac: ENC[AES256_GCM,data:z55hymehbXwQkTN35lyRU7Pu6jcuemfylfSg6g8SdVlZTEX6/1jet3NsmA5mcccX/1u/Cq4Ovu8ZKvWNNk8Tho9as5z5MTxBdEGMky80Lk6wS2IyT1RdX/g012vb0fvzK3xx8kFBoCxoiqcDh3nP91sJBJrfnvqNsFGM2j/cO30=,iv:AZcRqLnyBmKGbsBSlh5vv976iJCDSXEKqg3++A/j+g4=,tag:0ZzIaPY5+QQ86PW3DKjYuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
