apiVersion: v1
kind: Secret
metadata:
    name: api-service-env
    namespace: cfd
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:QnUImmGj3jTEGtG8QmjCCMYpDJeDwqysdQn0JhrDDNcFCGnug1Kw7sf/+uFaxxRLRD+4gWwf98pfji+X+4aQyzKj0rg0brRZLrmx+RYJvJnk67Z/UnPL6qS0p4QGeS3226GyZsQE2J3jGX+fD5eOB65cX3oHpPPhRNAqToms2cAEQBeQ9BBDsFusURI0LeJekfFXqe1tmKc=,iv:UriPYDKvJvnQK3EoLiPE5yWLNeNq8qicJcPCKTONT5g=,tag:guWoM4UOzG0yE1qjim/Cew==,type:str]
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcS84OGhqOVE4RTMxTXV5
            S1B0a1NzL1dHbXp5alFpZW5QblNiT2RaUkNNCmlDVzB3Qk4wTGRCRHRzd3pScnVa
            YnVWRkhaSitINC8rUzBiMXlXUnZFUG8KLS0tIDdiL25ma2E5TENac2tYMm1qaU1M
            RHZ4Mk4vM3RXRFBNeXA2RkdyMlAvb3MKtcsaefgplWkaqNTZl74cAWlVFnEFf+1M
            VImsPnBS9v2SgCBdC1EU0MH4EsZrKkSGmMM4Q+fTfwAKzRlUPxAAKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T06:22:06Z"
    mac: ENC[AES256_GCM,data:zWGlpABTNU9tPzyyIaKj+e1+YcE2MHSfxTVeZs6o3ob0iugQfs63Na+BAe+d7FlGL0Mk328yF4+rBj0H2FhVnKI+Qx+w/Kcv7VIXC8WODyI/CjcNNvSUvdlyw8QFZm4N91U8Kl+WuA+WvLOHD7isWZm8r2TC3DqacqbFhhA5lpI=,iv:Q5G81obF83xx6pf3m5t3YYA94BIzv8FQXGZgb9GuDXw=,tag:lUDhbGSp6yUushz6sfWICA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
