apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ebX/hapG00/Xz7vRplvCpqwPEu5V5hPFKBfdcIY4sl/A5PwemYo0Zb6d1IJ8nsVcZsp1m3kHC3XfF7qEPIVmOcAGoxK2qLTWTCtwRp67C1PM4qaOCAF4rVjkeFH8PYM4NpY58MPqJ48u7DPK3p+ItMWRa/fwi9VMVBw8U+5l4U1OdLewD8+7TwpJ/Q7448j3MKh38slJ0Rp1YT8b6/ZNNEdsnd9qFb7Syw1MxRi/qNGllgQhLE/JkyQQpT5kVycNLZjJa7AXoW3uIXt4rOyBAJngPB6RPgSTo+jgH5aYq2UeoCt4Koegin0Bj3c=,iv:vaYSZp/r/qVb4J9jfeaZNNUQTYl65FCluge0RJ0sVxc=,tag:NeJrHwRSWyAAmb0pt22W/A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cfd
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcUtaWk11YVhHNHhuUjQz
            eU53MVVBcVJjQ0s3UzQvTHN0ZGFHYmI2UzJNCkxWU1htV3JFdFlPeWY4MUE0TFNQ
            c1orTFd2UjlCTGF6RkZHVHk3ZWtKUWMKLS0tIGJjZTRSUlNNTno3V01SczVSdk43
            MG44Z2Y5VlVpbFBrTHVqcFNuQ05ST1UKoEbmtyqqSivIjOdtBJmwvt55fJ0GUHg5
            b+46ElYrBaYd1PH4l5b/rkkt4OrmWllHok9J6cqppU0+jS4bBN7YkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T10:46:03Z"
    mac: ENC[AES256_GCM,data:lf87EwP6YIZPdg1NNzaxWBe9XgKKV/0HVEUghdX8pzRY21V04MIK7VOAZxmrycF+yobSnbKY39aiakLIlXcILyWfsnNEVOCJOGhzfhZC9xf+0q/L8sGwhMq/NnnT9+MhJ1ivTpaCs3TEpawBOjBE+Ds3PPwpHqbNpLG0kuy2bCQ=,iv:bbtR6FPPFqksCgVVmqun1ViaioJLm/A2YeLDI2qzrL8=,tag:/yLW22g1gRi+bydAb/dW5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
