apiVersion: v1
kind: Secret
metadata:
    name: engine-service-env
    namespace: cfd
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:MpJLDBbECcIa5rfF7dFlSxMsYtXbc6SacnqiAbfCSbKNU35xWHUY9WGs8iLkD89vDvpSF3gzSHcfpmSBZb7AZlBuTvqoHoX6qJSZI1AUYWhOygEgms+1cenGqF1fxxL3y3mMhjm2xbAluWAxecVzy5HU6auEsKLnMlF125M2Lv7ZrgDTThwHqjTKt8TwRVUhEgw0YBpv+vU=,iv:K1KKDPNzex3hpF6KaURCNKeQN43EcB4DtycUCR57UFE=,tag:djztfKOBLiNOlV48/zetCA==,type:str]
sops:
    age:
        - recipient: age1de6c8ncpe08snevzsfraf8j7fj4lhuky837vmvm690982dell3csh6mu20
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbVhBaXhObzFaTVVOcDRn
            SnNVOEFKMGV0eWZsZHhGZmNPUTJYR3RFTFZBCmZoQ3A3Z1pMU1MraWxhTTVjekFz
            eUZFN004ZndUNHV6OGw4SzJPRHR1TWMKLS0tIDlZVkVjTWF1ME04VGM1UHlnNndi
            WXVzVG5nd2pSMFFhS0kzdGFJYnFZeTQKmR3xlMUbm+rI4X0ZFzfUWLVOY9QbTWud
            hJx99pdRWDaI9q7A7osw7z/F//+4CL7SVnYrOEkvU7zNjqVhf76SoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T06:16:43Z"
    mac: ENC[AES256_GCM,data:E+glTB/XZ6FXNoGp41YCRBCK+oP2tBi6uw7OCzHrTrUDKfsvwXhHirY7x1/dxkaelLOvXkiKWRtHF1R13hxO1s8CRuKzsnMtASB+jQC5XW1FrEh7to8euE0EMqmntFbPqTXsNDlXGEjMNZlEOHBT6WyAg0wdtjZLxBfT19ny+tA=,iv:EJG0AX4ZoCVJ8ypax/DKnYKlHVt/3mcSwBQ7kKzyZgU=,tag:mI6L4t2juY0GtAeIHcGZyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
