apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cfd
resources:
  - ../../base/cfd
  # - cloudflare.yaml
  # - cloudflare-secret.yaml
  # - cfd-container-env-secret.yaml
  - web-ingress.yaml
