apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: cfd
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
